/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        try {
            //here de-jdbc is database name, root is username and password is null. Fix them for your database settings.
            Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/de_jdbc", "root","0000");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from product");
            while (rs.next()){
            System.out.println(rs.getInt(1) + " " + rs.getString(2) + " "
            + rs.getDate(3) + " " + rs.getString(4)
            + " " + rs.getInt(5));
            }
            con.close();
        }   catch (Exception e) {System.out.println(e);}
    }
}
